# Generated by Django 5.2.7 on 2026-01-11 20:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessedWebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Processed Webhook Event",
                "verbose_name_plural": "Processed Webhook Events",
                "db_table": "processed_webhook_events",
                "ordering": ["-processed_at"],
                "indexes": [
                    models.Index(
                        fields=["event_id"], name="processed_w_event_i_c57493_idx"
                    ),
                    models.Index(
                        fields=["processed_at"], name="processed_w_process_ba066e_idx"
                    ),
                ],
            },
        ),
    ]
