[pytest]
DJANGO_SETTINGS_MODULE = MarketLink.settings
python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
addopts =
    --reuse-db
    --nomigrations
    --cov=payments
    --cov=orders
    --cov=users
    --cov=vendors
    --cov=services
    --cov-report=html
    --cov-report=term-missing
    -v
testpaths = payments orders users vendors services