# Generated by Django 5.2.7 on 2026-01-11 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="vendors.vendorprofile",
            ),
        ),
        migrations.AddField(
            model_name="servicevariant",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="services.service",
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["vendor", "is_active"], name="services_vendor__4299f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["created_at"], name="services_created_22da02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicevariant",
            index=models.Index(
                fields=["service"], name="service_var_service_19c3db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicevariant",
            index=models.Index(fields=["stock"], name="service_var_stock_f0d0a8_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="servicevariant",
            unique_together={("service", "name")},
        ),
    ]
