# Generated by Django 5.2.7 on 2026-01-11 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor Profile",
                "verbose_name_plural": "Vendor Profiles",
                "db_table": "vendor_profiles",
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="vendor_prof_is_acti_3a5a6c_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="vendor_prof_created_f04b48_idx"
                    ),
                ],
            },
        ),
    ]
