# Generated by Django 5.2.7 on 2026-01-11 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("services", "0001_initial"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="repairorder",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="repairorder",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="services.servicevariant",
            ),
        ),
        migrations.AddField(
            model_name="repairorder",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="vendors.vendorprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="repairorder",
            index=models.Index(
                fields=["customer", "status"], name="repair_orde_custome_730dfe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repairorder",
            index=models.Index(
                fields=["vendor", "status"], name="repair_orde_vendor__aacab0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repairorder",
            index=models.Index(
                fields=["created_at"], name="repair_orde_created_b4f08e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repairorder",
            index=models.Index(fields=["status"], name="repair_orde_status_468476_idx"),
        ),
    ]
